"""Bridge to the EXTERNAL verification repository (untrusted-engine policy).

The research engine is untrusted. After an experiment is frozen this module
  1. stages a self-contained copy of exactly what runs (engine/, features/, frozen/v1/, event.py,
     EVENT_SPEC.yaml) and checks the copies against FROZEN_MANIFEST hashes;
  2. generates the adapter the verifier expects (events / features / targets / fit_predict_fold);
  3. invokes <verifier>/scripts/verify_research.py once per (primary target x model) path - RIDGE, SPLINE and XGB, strong
     mode - with the correct --bar-interval --target --target-horizon --lockbox-start --mode flags;
  4. reports research-family status SEPARATELY from the global verdict. Exit code 2 is never a pass;
  5. refuses any verifier checkout that is not the commit pinned in frozen/v1/VERIFIER_PIN.yaml;
  6. never hands the verifier OOS/lockbox rows: the data it receives is cut to the stage's partition (IS: rows before
     development_end; OOS-stage: rows before oos_end). The verifier's lockbox audit needs rows to withhold, so the last
     ``stage_holdout_fraction`` of the staged span (frozen in VERIFIER_PIN.yaml) is passed as --lockbox-start.
"""
from __future__ import annotations

import json
import re
import shutil
import subprocess
import sys
from pathlib import Path

from engine import trial_registry as reg
from engine.common import CODE_ROOT, EngineError, load_frozen, load_yaml, model_names, primary_target_names, sha256_file
from engine.event_contract import load_spec
from engine.partitions import load_bars_before, parse_partitions
from engine.experiment_lifecycle import MANIFEST, experiment_dir, verify_manifest

RESEARCH_FAMILIES = ("research_contract", "research_causality", "walkforward", "ml_leakage", "lockbox")
HEURISTIC_FAMILIES = ("ml_static_scan",)
_LINE = re.compile(r"^\[(\w+)\s*\]\s+(\S+)\s+\((\w+)\)")

ADAPTER_SOURCE = '''"""GENERATED by scripts/verify_experiment.py -- do not edit. Research adapter for {experiment_id}.

Exposes the frozen engine to the external verifier using the information clock:
bars are open-stamped, event_time is a bar COMPLETION time, forward windows start at the first bar
whose open >= event_time. fit_predict_fold uses the frozen {model} model only.
Non-model-eligible validation rows (warm-up, non-finite features) receive prediction 0.0 because the
verifier requires one finite prediction per row; such rows are excluded from all research statistics.
"""
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE))

import numpy as np
import pandas as pd

from engine import event_contract as ec
from engine.common import load_frozen
from engine.feature_engine import compute_features, feature_names
from engine.model_engine import FrozenModel
from engine.target_engine import compute_primary_targets, to_long

FROZEN = load_frozen()
SPEC = ec.load_spec(HERE / "EVENT_SPEC.yaml")
MODULE = ec.load_event_module(HERE / "event.py")
MODEL = "{model}"
NAMES = feature_names(FROZEN)


def events(bars):
    ev, _ = ec.generate_events(MODULE, bars, SPEC, FROZEN)
    return ev[["event_id", "event_time", "direction"]]


def features(bars, events):
    out = compute_features(bars, events, FROZEN)
    return pd.DataFrame(out)


def targets(bars, events):
    if len(events) == 0:
        return pd.DataFrame({{"event_id": [], "target_name": [], "target_start": [], "target_end": [], "target_value": []}})
    return to_long(compute_primary_targets(bars, events, FROZEN))


def fit_predict_fold(features, targets, train_ids, validation_ids, target_name):
    if "target_name" in targets.columns:
        lab = targets[targets["target_name"] == target_name].set_index("event_id")["target_value"]
    else:
        lab = targets.set_index("event_id")[target_name]
    table = features.set_index("event_id")[NAMES]
    finite = np.isfinite(table.to_numpy(dtype=float)).all(axis=1)
    finite = pd.Series(finite, index=table.index)
    train_ids = [i for i in train_ids if i in lab.index and bool(finite.loc[i]) and np.isfinite(lab.loc[i])]
    val_ids = list(validation_ids)
    pred = pd.Series(0.0, index=val_ids)
    usable = [i for i in val_ids if bool(finite.loc[i])]
    if len(train_ids) >= 10 and usable:
        model = FrozenModel(MODEL, FROZEN).fit(table.loc[train_ids].reset_index(drop=True), lab.loc[train_ids].to_numpy(float))
        pred.loc[usable] = model.predict(table.loc[usable].reset_index(drop=True))
    return pd.DataFrame({{"event_id": val_ids, "prediction": pred.to_numpy(float)}})
'''


def verifier_pin() -> dict:
    return load_yaml(CODE_ROOT / "frozen" / "v1" / "VERIFIER_PIN.yaml")


def stage_holdout_start(first_bar, cutoff, pin: dict | None = None) -> str:
    """UTC date (YYYY-MM-DD) passed to the verifier as --lockbox-start for a stage whose data ends before ``cutoff``.

    The verifier never receives rows at/after the stage partition, yet its lockbox audit is UNVERIFIED when it has no events to
    withhold. A frozen holdout inside the staged span (the last ``stage_holdout_fraction``, >= ``stage_holdout_min_days``) solves
    that without handing it any OOS/lockbox row. Deterministic: depends only on the first staged bar and the partition date."""
    import pandas as pd
    pin = pin or verifier_pin()
    first = pd.Timestamp(first_bar).tz_convert("UTC").normalize()
    cut = pd.Timestamp(cutoff).tz_convert("UTC")
    span = cut - first
    hold = max(pd.Timedelta(days=int(pin["stage_holdout_min_days"])), span * float(pin["stage_holdout_fraction"]))
    start = (cut - hold).floor("D")
    if start <= first:
        raise EngineError(f"staged span {first:%Y-%m-%d}..{cut:%Y-%m-%d} is too short for a verifier holdout")
    return f"{start:%Y-%m-%d}"


def calendar_years_before(index, holdout_start: str) -> list[int]:
    """UTC calendar years that have staged bars before the verifier holdout. The verifier's folds are UTC calendar years; with fewer
    than 3 of them no audited fold has later (non-holdout) rows, so its future-poisoning checks are 'not applicable' (UNVERIFIED)."""
    import pandas as pd
    idx = pd.DatetimeIndex(index).tz_convert("UTC")
    return sorted({int(y) for y in idx[idx < pd.Timestamp(holdout_start, tz="UTC")].year.unique()})


def check_verifier_pin(verifier_repo: Path) -> str:
    """The external verifier must be exactly the pinned commit (never an arbitrary main)."""
    pin = verifier_pin()
    try:
        head = subprocess.run(["git", "-C", str(verifier_repo), "rev-parse", "HEAD"], capture_output=True, text=True, check=True).stdout.strip()
    except Exception as e:  # noqa: BLE001
        raise EngineError(f"cannot read the verifier checkout's commit ({verifier_repo}): {e}") from e
    if head != pin["commit"]:
        raise EngineError(f"verifier checkout is at {head}, but frozen/v1/VERIFIER_PIN.yaml pins {pin['commit']}. "
                          f"Check out the pinned commit; this engine never invokes an unpinned verifier.")
    dirty = subprocess.run(["git", "-C", str(verifier_repo), "status", "--porcelain"], capture_output=True, text=True).stdout.strip()
    if dirty:
        raise EngineError("the pinned verifier checkout has local modifications; refusing to run a modified verifier")
    return head


def stage_verification_dir(ws: reg.Workspace, experiment_id: str, models: list[str] | None = None) -> Path:
    """Copy the code that will run into experiments/<id>/verification/stage, check it against the manifest, and write one
    adapter per frozen model (adapter_RIDGE.py, adapter_SPLINE.py, adapter_XGB.py)."""
    verify_manifest(ws, experiment_id)                         # raises if mutated
    d = experiment_dir(ws, experiment_id)
    manifest = json.loads((d / MANIFEST).read_text())
    stage = d / "verification" / "stage"
    if stage.exists():
        shutil.rmtree(stage)
    stage.mkdir(parents=True)
    for sub in ("engine", "features"):
        (stage / sub).mkdir()
        for p in sorted((CODE_ROOT / sub).glob("*.py")):
            shutil.copy2(p, stage / sub / p.name)
    shutil.copytree(CODE_ROOT / "frozen", stage / "frozen")
    shutil.copy2(CODE_ROOT / "ENGINE_VERSION", stage / "ENGINE_VERSION")
    for f in ("event.py", "EVENT_SPEC.yaml"):
        shutil.copy2(d / f, stage / f)
    if sha256_file(stage / "event.py") != manifest["hashes"]["event_py"] or \
            sha256_file(stage / "EVENT_SPEC.yaml") != manifest["hashes"]["event_spec"]:
        raise EngineError("staged event files differ from the frozen manifest")
    for rel, h in manifest["hashes"]["frozen_files"].items():
        if sha256_file(stage / rel) != h:
            raise EngineError(f"staged frozen file differs from manifest: {rel}")
    for m in (models or model_names(load_frozen())):
        (stage / f"adapter_{m}.py").write_text(ADAPTER_SOURCE.format(experiment_id=experiment_id, model=m))
    return stage


def parse_verifier_output(stdout: str) -> dict:
    fams, verdict = {}, None
    for line in stdout.splitlines():
        m = _LINE.match(line.strip())
        if m:
            fams[m.group(2)] = m.group(1).strip()
        if line.startswith("VERDICT:"):
            verdict = line.split(":", 1)[1].strip()
    return {"family_status": fams, "verdict": verdict}


def classify(exit_code: int, parsed: dict) -> dict:
    """Never treats exit code 2 as PASS; research families are judged separately from the global verdict."""
    fs = parsed["family_status"]
    research = {f: fs.get(f, "MISSING") for f in RESEARCH_FAMILIES}
    research_ok = all(v == "PASS" for v in research.values())
    other = {f: s for f, s in fs.items() if f not in RESEARCH_FAMILIES}
    if exit_code == 0 and research_ok:
        label = "VERIFIED"
    elif exit_code == 1 or any(v == "FAIL" for v in research.values()):
        label = "FAILED"
    elif exit_code == 2 and research_ok:
        label = "RESEARCH_FAMILIES_PASS_GLOBAL_INCOMPLETE"
    else:
        label = "INCOMPLETE"
    return {"label": label, "research_families": research, "other_families": other,
            "global_verdict": parsed["verdict"], "exit_code": exit_code,
            "research_results_valid": label in ("VERIFIED", "RESEARCH_FAMILIES_PASS_GLOBAL_INCOMPLETE")}


def verifier_command(verifier_repo: Path, adapter: Path, source: Path, data: str, *, target: str, horizon_bars: int,
                     lockbox_start: str, mode: str, bar_interval: str, timestamp_col: str,
                     report_prefix: Path, skip_tests: bool = False, seed: int = 1729) -> list[str]:
    cmd = [sys.executable, str(Path(verifier_repo) / "scripts" / "verify_research.py"),
           "--adapter", str(adapter), "--source", str(source), "--data", str(data),
           "--timestamp-col", timestamp_col, "--bar-interval", bar_interval, "--target", target,
           "--target-horizon", f"{horizon_bars}bars", "--lockbox-start", lockbox_start, "--mode", mode,
           "--seed", str(seed), "--report-prefix", str(report_prefix)]
    if skip_tests:
        cmd.append("--skip-tests")
    return cmd


def overall_label(results: list[dict]) -> str:
    labels = [r["label"] for r in results]
    for bad in ("FAILED", "INCOMPLETE"):
        if bad in labels:
            return bad
    if all(l == "VERIFIED" for l in labels):
        return "VERIFIED"
    return "RESEARCH_FAMILIES_PASS_GLOBAL_INCOMPLETE"


def promotion_capable_targets(frozen) -> list[str]:
    """Every primary target takes part in the 24 selection trials, so every one of them can reach IS_SHORTLIST_ELIGIBLE,
    AWAITING_HUMAN_OOS_APPROVAL and OOS_CONFIRMED (4 primary targets x 3 models = 12 strong-mode paths). Which targets happen to be
    rejected at IS time is NOT used to skip verification: a retroactive or later change must never find an unverified path."""
    return list(primary_target_names(frozen))


def run_verification(ws: reg.Workspace, experiment_id: str, verifier_repo: str | Path, data: str, *,
                     stage_name: str = "IS", mode: str = "strong", models: list[str] | None = None,
                     timestamp_col: str = "timestamp", targets: list[str] | None = None,
                     skip_verifier_tests: bool = False, record: bool = True, verbose: bool = True) -> dict:
    """Verify every (target x model) path capable of promotion: RIDGE, SPLINE and XGB (default), strong mode."""
    frozen = load_frozen()
    vr = Path(verifier_repo).resolve()
    script = vr / "scripts" / "verify_research.py"
    if not script.exists():
        raise EngineError(
            f"{script} not found. The research verification layer must be present in the verifier checkout "
            f"(it is on branch claude/relaxed-lamport-119uli of engine-verification-, not on main at the time of writing). "
            f"This engine does not modify or copy the verifier.")
    check_verifier_pin(vr)
    exp = reg.experiment_row(ws, experiment_id)
    if exp["status"] == "DRAFT":
        raise EngineError(f"{experiment_id} must be frozen before verification")
    if stage_name not in ("IS", "OOS"):
        raise EngineError("stage must be IS or OOS")
    d = experiment_dir(ws, experiment_id)
    spec = load_spec(d / "EVENT_SPEC.yaml")
    parts = parse_partitions(spec["partitions"])
    cutoff = parts.development_end if stage_name == "IS" else parts.oos_end
    if stage_name == "OOS" and not reg.oos_spent(ws, experiment_id):
        raise EngineError("OOS-stage verification is only available after the human-approved OOS has been spent")
    models = models or model_names(frozen)
    all_targets = promotion_capable_targets(frozen)
    targets = targets or all_targets
    unknown = sorted(set(targets) - set(all_targets))
    if unknown:
        raise EngineError(f"unknown primary targets {unknown}")
    warnings_skipped = sorted(set(all_targets) - set(targets))
    stage = stage_verification_dir(ws, experiment_id, models)
    # the verifier never sees rows beyond this stage's partition
    vdir = d / "verification"
    bars = load_bars_before(data, cutoff, timestamp_col)
    stage_data = vdir / f"data_{stage_name}.parquet"
    holdout_start = stage_holdout_start(bars.index.min(), cutoff)
    years = calendar_years_before(bars.index, holdout_start)
    warnings = []
    if warnings_skipped:
        warnings.append(f"PARTIAL VERIFICATION: promotion-capable targets {warnings_skipped} were NOT verified; an approval for any group on them will be refused")
    if len(years) < 3:
        warnings.append(f"only {len(years)} UTC calendar year(s) {years} of staged data precede the verifier holdout ({holdout_start}): the verifier's "
                        "future_label/future_feature poisoning checks need a fold with later rows, so strong-mode verification is expected to be "
                        "INCOMPLETE (UNVERIFIED), never a pass. Use a development window of at least 3 calendar years.")
        if verbose:
            print("WARNING:", warnings[-1], flush=True)
    bars.reset_index().rename(columns={"index": "timestamp"}).to_parquet(stage_data)
    horizons = {t["name"]: t["horizon_bars"] for t in frozen.target_bank["primary_targets"]}
    out_dir = vdir / "reports"
    out_dir.mkdir(parents=True, exist_ok=True)
    results, first = [], True
    for target in targets:
        for model in models:
            cmd = verifier_command(vr, stage / f"adapter_{model}.py", stage, str(stage_data), target=target,
                                   horizon_bars=horizons[target], lockbox_start=holdout_start, mode=mode,
                                   bar_interval=frozen.instrument["bar_interval"], timestamp_col="timestamp",
                                   report_prefix=out_dir / f"research_{stage_name}_{target}_{model}",
                                   skip_tests=skip_verifier_tests or not first)
            first = False                                   # repository_health runs once; research families run for every path
            if verbose:
                print("$", " ".join(cmd), flush=True)
            proc = subprocess.run(cmd, capture_output=True, text=True, cwd=str(vr))
            res = classify(proc.returncode, parse_verifier_output(proc.stdout))
            res.update({"target": target, "model": model, "mode": mode, "stage": stage_name, "command": cmd,
                        "stdout_tail": proc.stdout[-2500:], "stderr_tail": proc.stderr[-1200:]})
            results.append(res)
            if verbose:
                print(f"=> {target}|{model}: exit={proc.returncode} label={res['label']} (exit code 2 is NOT a pass)", flush=True)
    summary = {"experiment_id": experiment_id, "stage": stage_name, "verifier_repo": str(vr), "verifier_commit": verifier_pin()["commit"],
               "mode": mode, "stage_cutoff": f"{cutoff:%Y-%m-%d}", "verifier_holdout_start": holdout_start, "warnings": warnings, "models_verified": models, "targets_verified": targets, "overall": overall_label(results), "results": results}
    (vdir / f"verification_summary_{stage_name}.json").write_text(json.dumps(summary, indent=2, default=str))
    if record and stage_name == "IS":
        paths = {f"{r['target']}|{r['model']}": {"label": r["label"], "mode": r["mode"], "research_families": r["research_families"],
                                                  "research_results_valid": r["research_results_valid"]} for r in results}
        reg.set_verification(ws, experiment_id, paths, summary["overall"], frozen)
        if reg.is_revealed(exp) and not reg.oos_spent(ws, experiment_id) and (d / "results" / "results.json").exists():
            from engine import is_report
            is_report.write_is_report(ws, experiment_id)             # the IS report now shows the verification state
    return summary
