"""Bridge to the EXTERNAL verification repository (untrusted-engine policy).

The research engine is untrusted. After an experiment is frozen this module
  1. stages a self-contained copy of exactly what runs (engine/, features/, frozen/v1/, event.py,
     EVENT_SPEC.yaml) and checks the copies against FROZEN_MANIFEST hashes;
  2. generates the adapter the verifier expects (events / features / targets / fit_predict_fold);
  3. invokes <verifier>/scripts/verify_research.py once per primary target with the correct
     --bar-interval --target --target-horizon --lockbox-start --mode flags;
  4. reports research-family status SEPARATELY from the global verdict. Exit code 2 is never a pass.
"""
from __future__ import annotations

import json
import re
import shutil
import subprocess
import sys
from pathlib import Path

from engine import trial_registry as reg
from engine.common import CODE_ROOT, EngineError, load_frozen, primary_target_names, sha256_file
from engine.experiment_lifecycle import MANIFEST, experiment_dir, verify_manifest

RESEARCH_FAMILIES = ("research_contract", "research_causality", "walkforward", "ml_leakage", "lockbox")
HEURISTIC_FAMILIES = ("ml_static_scan",)
_LINE = re.compile(r"^\[(\w+)\s*\]\s+(\S+)\s+\((\w+)\)")

ADAPTER_SOURCE = '''"""GENERATED by scripts/verify_experiment.py -- do not edit. Research adapter for {experiment_id}.

Exposes the frozen engine to the external verifier using the information clock:
bars are open-stamped, event_time is a bar COMPLETION time, forward windows start at the first bar
whose open >= event_time. fit_predict_fold uses the frozen {model} model only.
Non-model-eligible validation rows (warm-up, non-finite features) receive prediction 0.0 because the
verifier requires one finite prediction per row; such rows are excluded from all research statistics.
"""
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE))

import numpy as np
import pandas as pd

from engine import event_contract as ec
from engine.common import load_frozen
from engine.feature_engine import compute_features, feature_names
from engine.model_engine import FrozenModel
from engine.target_engine import compute_primary_targets, to_long

FROZEN = load_frozen()
SPEC = ec.load_spec(HERE / "EVENT_SPEC.yaml")
MODULE = ec.load_event_module(HERE / "event.py")
MODEL = "{model}"
NAMES = feature_names(FROZEN)


def events(bars):
    ev, _ = ec.generate_events(MODULE, bars, SPEC, FROZEN)
    return ev[["event_id", "event_time", "direction"]]


def features(bars, events):
    out = compute_features(bars, events, FROZEN)
    return pd.DataFrame(out)


def targets(bars, events):
    if len(events) == 0:
        return pd.DataFrame({{"event_id": [], "target_name": [], "target_start": [], "target_end": [], "target_value": []}})
    return to_long(compute_primary_targets(bars, events, FROZEN))


def fit_predict_fold(features, targets, train_ids, validation_ids, target_name):
    if "target_name" in targets.columns:
        lab = targets[targets["target_name"] == target_name].set_index("event_id")["target_value"]
    else:
        lab = targets.set_index("event_id")[target_name]
    table = features.set_index("event_id")[NAMES]
    finite = np.isfinite(table.to_numpy(dtype=float)).all(axis=1)
    finite = pd.Series(finite, index=table.index)
    train_ids = [i for i in train_ids if i in lab.index and bool(finite.loc[i]) and np.isfinite(lab.loc[i])]
    val_ids = list(validation_ids)
    pred = pd.Series(0.0, index=val_ids)
    usable = [i for i in val_ids if bool(finite.loc[i])]
    if len(train_ids) >= 10 and usable:
        model = FrozenModel(MODEL, FROZEN).fit(table.loc[train_ids].reset_index(drop=True), lab.loc[train_ids].to_numpy(float))
        pred.loc[usable] = model.predict(table.loc[usable].reset_index(drop=True))
    return pd.DataFrame({{"event_id": val_ids, "prediction": pred.to_numpy(float)}})
'''


def stage_verification_dir(ws: reg.Workspace, experiment_id: str, model: str = "RIDGE") -> Path:
    """Copy the code that will run into experiments/<id>/verification/stage and check it against the manifest."""
    verify_manifest(ws, experiment_id)                         # raises if mutated
    d = experiment_dir(ws, experiment_id)
    manifest = json.loads((d / MANIFEST).read_text())
    stage = d / "verification" / "stage"
    if stage.exists():
        shutil.rmtree(stage)
    stage.mkdir(parents=True)
    for sub in ("engine", "features"):
        (stage / sub).mkdir()
        for p in sorted((CODE_ROOT / sub).glob("*.py")):
            shutil.copy2(p, stage / sub / p.name)
    shutil.copytree(CODE_ROOT / "frozen", stage / "frozen")
    shutil.copy2(CODE_ROOT / "ENGINE_VERSION", stage / "ENGINE_VERSION")
    for f in ("event.py", "EVENT_SPEC.yaml"):
        shutil.copy2(d / f, stage / f)
    if sha256_file(stage / "event.py") != manifest["hashes"]["event_py"] or \
            sha256_file(stage / "EVENT_SPEC.yaml") != manifest["hashes"]["event_spec"]:
        raise EngineError("staged event files differ from the frozen manifest")
    for rel, h in manifest["hashes"]["frozen_files"].items():
        if sha256_file(stage / rel) != h:
            raise EngineError(f"staged frozen file differs from manifest: {rel}")
    (stage / "adapter.py").write_text(ADAPTER_SOURCE.format(experiment_id=experiment_id, model=model))
    return stage


def parse_verifier_output(stdout: str) -> dict:
    fams, verdict = {}, None
    for line in stdout.splitlines():
        m = _LINE.match(line.strip())
        if m:
            fams[m.group(2)] = m.group(1).strip()
        if line.startswith("VERDICT:"):
            verdict = line.split(":", 1)[1].strip()
    return {"family_status": fams, "verdict": verdict}


def classify(exit_code: int, parsed: dict) -> dict:
    """Never treats exit code 2 as PASS; research families are judged separately from the global verdict."""
    fs = parsed["family_status"]
    research = {f: fs.get(f, "MISSING") for f in RESEARCH_FAMILIES}
    research_ok = all(v == "PASS" for v in research.values())
    other = {f: s for f, s in fs.items() if f not in RESEARCH_FAMILIES}
    if exit_code == 0 and research_ok:
        label = "VERIFIED"
    elif exit_code == 1 or any(v == "FAIL" for v in research.values()):
        label = "FAILED"
    elif exit_code == 2 and research_ok:
        label = "RESEARCH_FAMILIES_PASS_GLOBAL_INCOMPLETE"
    else:
        label = "INCOMPLETE"
    return {"label": label, "research_families": research, "other_families": other,
            "global_verdict": parsed["verdict"], "exit_code": exit_code,
            "research_results_valid": label in ("VERIFIED", "RESEARCH_FAMILIES_PASS_GLOBAL_INCOMPLETE")}


def verifier_command(verifier_repo: Path, stage: Path, data: str, *, target: str, horizon_bars: int,
                     lockbox_start: str, mode: str, bar_interval: str, timestamp_col: str,
                     report_prefix: Path, skip_tests: bool = False, seed: int = 1729) -> list[str]:
    cmd = [sys.executable, str(Path(verifier_repo) / "scripts" / "verify_research.py"),
           "--adapter", str(stage / "adapter.py"), "--source", str(stage), "--data", str(data),
           "--timestamp-col", timestamp_col, "--bar-interval", bar_interval, "--target", target,
           "--target-horizon", f"{horizon_bars}bars", "--lockbox-start", lockbox_start, "--mode", mode,
           "--seed", str(seed), "--report-prefix", str(report_prefix)]
    if skip_tests:
        cmd.append("--skip-tests")
    return cmd


def overall_label(results: list[dict]) -> str:
    labels = [r["label"] for r in results]
    for bad in ("FAILED", "INCOMPLETE"):
        if bad in labels:
            return bad
    if all(l == "VERIFIED" for l in labels):
        return "VERIFIED"
    return "RESEARCH_FAMILIES_PASS_GLOBAL_INCOMPLETE"


def run_verification(ws: reg.Workspace, experiment_id: str, verifier_repo: str | Path, data: str, *,
                     mode: str = "strong", model: str = "RIDGE", timestamp_col: str = "timestamp",
                     targets: list[str] | None = None, skip_verifier_tests: bool = False, verbose: bool = True) -> dict:
    frozen = load_frozen()
    vr = Path(verifier_repo).resolve()
    script = vr / "scripts" / "verify_research.py"
    if not script.exists():
        raise EngineError(
            f"{script} not found. The research verification layer must be present in the verifier checkout "
            f"(it is on branch claude/relaxed-lamport-119uli of engine-verification-, not on main at the time of writing). "
            f"This engine does not modify or copy the verifier.")
    exp = reg.experiment_row(ws, experiment_id)
    if exp["status"] not in ("FROZEN", "REVEALED"):
        raise EngineError(f"{experiment_id} must be frozen before verification")
    camp = reg.campaign_row(ws, exp["campaign_id"])
    stage = stage_verification_dir(ws, experiment_id, model)
    horizons = {t["name"]: t["horizon_bars"] for t in frozen.target_bank["primary_targets"]}
    out_dir = experiment_dir(ws, experiment_id) / "verification" / "reports"
    out_dir.mkdir(parents=True, exist_ok=True)
    results = []
    for target in (targets or primary_target_names(frozen)):
        cmd = verifier_command(vr, stage, data, target=target, horizon_bars=horizons[target],
                               lockbox_start=camp["lockbox_start"], mode=mode, bar_interval=frozen.instrument["bar_interval"],
                               timestamp_col=timestamp_col, report_prefix=out_dir / f"research_{target}",
                               skip_tests=skip_verifier_tests)
        if verbose:
            print("$", " ".join(cmd), flush=True)
        proc = subprocess.run(cmd, capture_output=True, text=True, cwd=str(vr))
        parsed = parse_verifier_output(proc.stdout)
        res = classify(proc.returncode, parsed)
        res.update({"target": target, "command": cmd, "stdout_tail": proc.stdout[-3000:], "stderr_tail": proc.stderr[-1500:]})
        results.append(res)
        if verbose:
            print(proc.stdout[-2500:], flush=True)
            print(f"=> {target}: exit={proc.returncode} label={res['label']} (exit code 2 is NOT a pass)", flush=True)
    summary = {"experiment_id": experiment_id, "verifier_repo": str(vr), "mode": mode, "model_verified": model,
               "overall": overall_label(results), "results": results}
    (experiment_dir(ws, experiment_id) / "verification" / "verification_summary.json").write_text(
        json.dumps(summary, indent=2, default=str))
    reg.update_experiment(ws, experiment_id, research_verification=summary["overall"])
    return summary
